name: arisan-app
services:
- name: backend
  source_dir: backend
  dockerfile_path: Dockerfile
  github:
    repo: your-username/arisan-app
    branch: main
    deploy_on_push: true
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: NODE_ENV
    value: production
  - key: DATABASE_URL
    value: ${DATABASE_URL}
  - key: JWT_SECRET
    value: ${JWT_SECRET}
  - key: JWT_EXPIRES_IN
    value: 7d
  - key: PORT
    value: 3000
  - key: FRONTEND_URL
    value: ${APP_URL}
  - key: AWS_REGION
    value: ${AWS_REGION}
  - key: AWS_ACCESS_KEY_ID
    value: ${AWS_ACCESS_KEY_ID}
  - key: AWS_SECRET_ACCESS_KEY
    value: ${AWS_SECRET_ACCESS_KEY}
  - key: AWS_S3_BUCKET_NAME
    value: ${AWS_S3_BUCKET_NAME}
  - key: AWS_ENDPOINT
    value: ${AWS_ENDPOINT}
  - key: AWS_PUBLIC_URL
    value: ${AWS_PUBLIC_URL}
  http_port: 3000
  routes:
  - path: /api
  health_check:
    http_path: /health
    initial_delay_seconds: 30
    period_seconds: 10
    timeout_seconds: 3
    success_threshold: 1
    failure_threshold: 3

- name: frontend
  source_dir: frontend
  dockerfile_path: Dockerfile
  github:
    repo: your-username/arisan-app
    branch: main
    deploy_on_push: true
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 80
  routes:
  - path: /

databases:
- name: arisan-db
  engine: MYSQL
  version: "8"
  cluster_name: arisan-db-cluster
  db_name: arisan_app
  db_user: arisan_user
  production: true

domains:
- domain: your-domain.com
  type: PRIMARY
- domain: www.your-domain.com
  type: ALIAS